### ISSUE TITLE
Multi object baking not working

### ISSUE THREAD

**Issue by AsgerSuhr** [AsgerSuhr/UDIM_baking#2]
seems like it doesn't work with multiple objects in one?

**Comment by pokeheadroom** [comment]
was this fixed? i believe i may have this same issue, i say this since im trying to bake a level with multiple platforms and have had no luck baking it.
i also rolled back to an earlier version of blender to make sure this wasn't specific to 2.93 only and unfortunately i haven't been able to bake my level.

![image](https://user-images.githubusercontent.com/66020696/130359400-373e90ad-4601-42da-82a1-6c2a87a7fd1b.png)
